---
kind: Service
apiVersion: v1
metadata:
  name: dbs
  namespace: foxden
spec:
  selector:
    app: dbs
  ports:
    - port: 8310
      targetPort: 8310
      name: foxden
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dbs
  name: dbs
  namespace: foxden
spec:
  selector:
    matchLabels:
      app: dbs
  replicas: 1
  template:
    metadata:
      labels:
        app: dbs
        env: k8s
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8310"
    spec:
      containers:
      - image: ghcr.io/chesscomputing/databookkeeping:v0.0.1-dev3
        name: dbs
        imagePullPolicy: Always
        env:
          - name: CHESS_FOXDEN_CONFIG
            value: /etc/secrets/.foxden.yaml
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "8000m"
        livenessProbe:
          httpGet:
            path: /api
            port: 8310
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
        - containerPort: 8310
          protocol: TCP
          name: foxden
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: foxden-secrets
